server:
  port: 10003
eureka:
  instance:
    hostname: eureka10003.com
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZoon: http://eureka10001.com:10001/eureka,http://eureka10002.com:10002/eureka
spring:
  application:
    name: eureka03