server:
  port: 10001
eureka:
  instance:
    #eureka注册名
    hostname: eureka10001.com
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: #将当前项目注册进eureka注册中心的注册地址中去
      defaultZone : http://eureka10002.com:10002/eureka/
spring:
  application:
    name: eureka01