server:
  port: 7777
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka10001.com:10001/eureka/,http://eureka10002.com:10002/eureka/
feign:
  hystrix:
    enabled: true