server:
  port: 10002
eureka:
  instance:
    hostname: eureka10002.com
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka10001.com:10001/eureka
spring:
  application:
    name: eureka02